### ISSUE TITLE
Enemy idle walk

### ISSUE THREAD

**Issue by stedavkle** [IlluminatedTreeStudios/marama#12]
Make the Enemy lost in life. \n It should walk when around when no player is in sight. \n Maybe a option would be to define a few spawn locations where the enemy 'spawns' when the player enters a specific area. \n Somewhat like a Schrödinger's Enemy. \n You cant see the enemy walking when not near, therefore id does not make sense to let him walk

**Comment by Stephandi94** [comment]
Basic Functionality has been implemented
