### ISSUE TITLE
Glowing player

### ISSUE THREAD

**Issue by stedavkle** [IlluminatedTreeStudios/marama#7]
Attach a lightsource to the player. \n The brightness is defined by the life.

**Comment by TinaTruong023** [comment]
- [x] Mechanic of Health attached to Light 

Implementation through mesh and point lights attached to player:
- mesh glow
- point lights around character
- depending on health value intensity of glow and lights will adjust to it
- several parameters for mesh
       - pulsating effect, edge glow, or just plain glow
- instances of master material

_Might add texture to achieve a better visual of "glow"
Perhaps a better way in general is to use/combine with particle effects_
